Improvements
G-Core/cdn-stats-datasource-plugin pull request #1
Opened 2021-04-02 17:19 UTC by denisz

Fix types
Renaming types with prefix GC
Auth method only api tokens (APIKey XXX)
Add support unit
Add more info about api tokens
Add new report bandwidth
Add debounce to GCInput
Add support for adjusting legend

2021-04-04 15:09 UTC, denisz commented
@ivishnevs Please, don't forget to make review! 👀

2021-04-05 08:39 UTC, ivishnevs requested changes

2021-04-05 08:39 UTC, ivishnevs commented on src/times.ts
> +  static MILLISECOND = 1000;
MILLISECOND видно лишнее тут

2021-04-05 08:39 UTC, ivishnevs commented on src/regions.ts
> +export const regions = [
Это вске регионы ?

2021-04-05 08:39 UTC, ivishnevs commented on src/plugin.json
> +          "content": "APIKey {{ .SecureJsonData.apiKey }}"
теперь не останется возможности bearer использовать 
APIKey или Bearer должны к .SecureJsonData.apiKey лепиться в зависимости от юз кейза

2021-04-05 08:53 UTC, denisz commented on src/times.ts
> +  static MILLISECOND = 1000;
Нет, нужно в getTimeField исправить на val[0] * TimeInSeconds. MILLISECOND

2021-04-05 08:54 UTC, denisz commented on src/regions.ts
> +export const regions = [
Взял из документации. Есть запрос на получение регионов из биллинга, но они еще не поддерживают перманентные токены.

2021-04-05 10:30 UTC, denisz commented on src/plugin.json
> +          "content": "APIKey {{ .SecureJsonData.apiKey }}"
Исправил работу с токенами

2021-04-05 11:34 UTC, ivishnevs approved these changes

2021-04-05 11:45 UTC, merged